services:
  db:
    image: mysql:8.0
    container_name: mysql-library
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: library-backend
    restart: always
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://db:3306/library_db
      DB_USERNAME: library_user
      DB_PASSWORD: library_pass
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: libraryinlog@gmail.com
      MAIL_PASSWORD: crmexicyxrtepyxa
      MAIL_FROM: libraryinlog@gmail.com
    depends_on:
      - db

volumes:
  db_data:
